# Generated by Django 2.2.7 on 2021-01-12 06:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField(verbose_name='التاريخ ')),
            ],
            options={
                'verbose_name': ' تاريخ الحلقة ',
                'verbose_name_plural': ' تاريخ الحلقات ',
            },
        ),
        migrations.CreateModel(
            name='Centers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('center_name', models.CharField(max_length=255, verbose_name='اسم المركز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مركز الحلقة',
                'verbose_name_plural': ' مراكز الحلقات ',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255, verbose_name='اسم الحلقة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'الحلقة',
                'verbose_name_plural': ' الحلقات ',
            },
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('registration_number', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=200, verbose_name='اللقب')),
                ('firstname', models.CharField(max_length=200, verbose_name='الاسم ')),
                ('other_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الأب')),
                ('sex', models.CharField(choices=[('1', 'طلاب'), ('2', ' طالبات')], default='1', max_length=10, verbose_name='شطر الطلاب / الطالبات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='IkraApp.Centers', verbose_name='نوع الحلقة ')),
            ],
            options={
                'verbose_name': 'أستاذ',
                'verbose_name_plural': ' الأساتذة ',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('registration_number', models.AutoField(primary_key=True, serialize=False)),
                ('current_status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط')], default='active', max_length=10)),
                ('ikama_number', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name=' رقم الهوية / الأقامة')),
                ('firstname', models.CharField(max_length=200, verbose_name='الاسم ')),
                ('surname', models.CharField(max_length=200, verbose_name='اللقب')),
                ('other_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الأب')),
                ('sex', models.CharField(choices=[('1', 'طلاب'), ('2', ' طالبات')], default='1', max_length=10, verbose_name='شطر الطلاب / الطالبات')),
                ('date_of_birth', models.PositiveIntegerField(blank=True, null=True, verbose_name=' العمر ')),
                ('date_of_admission', models.DateField(default=django.utils.timezone.now, verbose_name=' تاريخ الإنظمام')),
                ('parent_mobile_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='الرجاء ادخال رقم الجوال بالطريقة الصحيحة!', regex='^[0-9]{10,15}$')], verbose_name='جوال الأب')),
                ('address', models.TextField(blank=True, verbose_name='العنوان ')),
                ('others', models.TextField(blank=True, verbose_name=' معلومات اخرى')),
                ('center_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='IkraApp.Centers', verbose_name=' المركز ')),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='IkraApp.Courses', verbose_name='نوع الحلقة ')),
                ('staff_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='IkraApp.Staffs', verbose_name=' شيخ الحلقة ')),
            ],
            options={
                'verbose_name': 'الطالب',
                'verbose_name_plural': ' الطلاب ',
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_exam_marks', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IkraApp.Courses', verbose_name='الحلقة')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IkraApp.Students', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': ' الدرجة ',
                'verbose_name_plural': ' الدرجات ',
            },
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('1', 'جيد'), ('2', 'جيد جدا'), ('3', 'ممتاز'), ('4', 'غير حافظ'), ('5', 'غائب')], default='1', max_length=10, verbose_name='الدرجة ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_id', models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='IkraApp.Attendance', verbose_name='تاريخ الحصة ')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='IkraApp.Students', verbose_name='الطالب ')),
            ],
            options={
                'verbose_name': 'رصد الدرجة',
                'verbose_name_plural': ' رصد الدرجات ',
            },
        ),
    ]
